### ISSUE TITLE
Evitar iteración para extraer info del channel

### ISSUE THREAD

**Issue by deivinsontejeda** [gallir/concurrencia_source_samples#1]
Hola @gallir 

Solo una pequeña sugerencia sobre el código escrito en Go.

Especificamente cuando iteras sobre los thread para ver la respeta del `channel`.

[gothreads.go](https://github.com/gallir/concurrencia_source_samples/blob/master/gothreads.go#L23-L25)
```go
    for i := 0; i < GOROUTINES; i++ {
        <-done
    }
```

La sugerencia es que en Go puedes evitar hacer esa iteración y preguntar directamente al channel por su valor asignado, el programa va a esperar hasta obtener todas los valores asignados, en este caso un output.

```go
<-done
```

te dejo el [gist](https://gist.github.com/deivinsontejeda/437faed7c9256d4b19c3) completo, si tienes alguna sugerencia acerca si es buena o mala practica esto que te digo, seria bueno escucharlo.

**Comment by gallir** [comment]
No funciona, esa iteración es para asegurar que han acabado todos los threads, con lo que pones sólo se espera al primero. El main puede acabar antes que acaben todos.

**Comment by deivinsontejeda** [comment]
En mi caso funcionó, lo he probado y espera todas las salidas. Incluso lo probe con un numero mas alto de `GORUTINES`. En tu caso no funcionó?

**Comment by deivinsontejeda** [comment]
Output:

```sh
○ go run concurrency.go
Hi, I'm thread 0
Hi, I'm thread 1
```

**Comment by gallir** [comment]
Porque no crea threads (por eso está el runtime.GOMAXPROCS(GOROUTINES) en el original).

BTW, https://gallir.wordpress.com/2015/02/01/las-cosas-que-no-soporto-que-las-diga-un-programador/ :-P

**Comment by deivinsontejeda** [comment]
En el original nunca *seteas* el `runtime.GOMAXPROCS`, estoy viendo este archivo https://github.com/gallir/concurrencia_source_samples/blob/master/gothreads.go y mi sugerencia fue sobre ese archivo.

Así que el comentario del articulo, no aplica :P (creo que estas haciendo referencia a otros archivos.)

**Comment by gallir** [comment]
Ah, sí, yo a https://github.com/gallir/concurrencia_source_samples/blob/master/gocounter.go Ese es una demasiado básico sin forzar la creación de más.

Pero es igual, prueba incrementando el numero de threads, o haz que uno de las goroutines se bloquee o tarde unos milisegundos más. Tu propuesta es errónea en cualquier caso, sólo espera a *un* mensaje (que no "valor asignado").
